# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Andrew Hendrickson
tagline:          'A Cognitive Scientist'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@athendri</a>.'
url:              http://hyde.getpoole.com

author:
  name:           'Drew Hendrickson'
  url:            https://twitter.com/athendri

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/drewhendrickson/drewhendrickson.github.io